### ISSUE TITLE
Section categories

### ISSUE THREAD

**Issue by erm** [florimondmanca/awesome-asgi#4]
First, I just want to save thank you for creating this repo! It is really exciting to see how the ASGI ecosystem is progressing, and I think this will be a useful addition.

My issue relates to the sections, particularly the placement of Bonnette and Mangum. They are similar in usage to ASGI middleware (wrapping an application), but they actually provide adapter classes - not middleware.

Should these projects be listed under the "Libraries" section, or should there be a new section created labeled "Adapters"?  I'd be happy to PR the changes based on discussion in this issue.

**Comment by florimondmanca** [comment]
Thanks a lot @erm!

I think the term adapter could be better suited to a few projects indeed. tartiflette-starlette is another example — it provides an ASGI adapter on top of a GraphQL engine. I also think about python-socketio (not in this list yet) which provides an ASGI adapter for socketio.

I’m not sure what to do with Ariadne though — it’s on this list primarily because it has an ASGI adapter built in, but Applications is definitely not the ideal category. Do you think it should be moved to Application frameworks instead?

Anyway, I’d be very happy to review a PR for all this. Feel free to shuffle projects around as seems fit!
