### ISSUE TITLE
ASGI Benchmark

### ISSUE THREAD

**Issue by Kludex** [florimondmanca/awesome-asgi#67]
I guess this benchmark can be included here: https://github.com/klen/py-frameworks-bench/

On which section would be ideal? :thinking:

**Comment by florimondmanca** [comment]
@Kludex Thanks. It's not that obvious to me as the benchmark is not _specifically focused on ASGI_ (which is something I think is important to hold onto for a list like this) — eg there's aiohttp, emmett, tornado, which are non-ASGI.

So it might be a better entry for "awesome-asyncio", or something like that?

**Comment by klen** [comment]
The benchmark is mainly focused on ASGI frameworks. 9 of 11 frameworks supports ASGI and runs in ASGI mode (emmet has ASGI support). `Tornado` and `aiohttp` have been added for speed comparison because of people asking, btw they both have plans to support ASGI. The benchmark's readme contains a mention about it. Just stopped by to make the note.

**Comment by florimondmanca** [comment]
@klen Thanks! That’s useful background info. Well, now I see there’s an explicit mention about ASGI right in the README introduction too.

I’m not sure where we’d put this tho. I guess a “Related projects” paragraph at the end of the “Application frameworks” section, with this as the sole project for now?

**Comment by florimondmanca** [comment]
I just suggested in #85 that we could rename « Toy projects as examples » to « Experiments and examples ». This would allow us to add a resource such as this one to the list. Thoughts?
